using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace SquadDash;

/// <summary>
/// Fields the AI sends when emitting an INBOX_MESSAGE_JSON block.
/// Timestamp, Id, and Read are generated by the host, not the AI.
/// </summary>
internal sealed class InboxMessageDto
{
    [JsonPropertyName("subject")]
    public string Subject { get; init; } = string.Empty;

    [JsonPropertyName("from")]
    public string From { get; init; } = string.Empty;

    [JsonPropertyName("body")]
    public string Body { get; init; } = string.Empty;

    [JsonPropertyName("attachments")]
    public IReadOnlyList<InboxAttachment> Attachments { get; init; } = [];

    [JsonPropertyName("actions")]
    public IReadOnlyList<InboxAction> Actions { get; init; } = [];
}

/// <summary>
/// Detects and extracts <c>INBOX_MESSAGE_JSON:</c> sentinel blocks from AI responses.
/// Uses the same structural pattern as <see cref="HostCommandParser"/>.
/// </summary>
internal static partial class InboxMessageParser
{
    [GeneratedRegex(
        @"(?s)^(?<body>.*?)(?:\n|^)\s*INBOX_MESSAGE_JSON:\s*(?<json>\{[\s\S]*\})\s*$",
        RegexOptions.CultureInvariant)]
    private static partial Regex InboxMessageJsonRegex();

    [GeneratedRegex(
        @"(?s)^(?<body>.*?)(?:\n|^)\s*```\w*\s*\n\s*INBOX_MESSAGE_JSON:\s*(?<json>\{[\s\S]*\})\s*```\s*$",
        RegexOptions.CultureInvariant)]
    private static partial Regex FencedInboxMessageJsonRegex();

    private static readonly JsonSerializerOptions ParseOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Attempts to extract an INBOX_MESSAGE_JSON block from <paramref name="text"/>.
    /// Returns true when the sentinel is found and the JSON is valid.
    /// <paramref name="body"/> receives the text before the block; <paramref name="dto"/> the parsed payload.
    /// </summary>
    internal static bool TryExtract(string text, out string body, out InboxMessageDto? dto)
    {
        body = text;
        dto  = null;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        var normalized = text.Replace("\r\n", "\n").Replace('\r', '\n');
        var match      = InboxMessageJsonRegex().Match(normalized);
        if (!match.Success)
            match = FencedInboxMessageJsonRegex().Match(normalized);
        if (!match.Success)
            return false;

        try
        {
            dto = JsonSerializer.Deserialize<InboxMessageDto>(match.Groups["json"].Value, ParseOptions);
            if (dto is null)
                return false;

            body = match.Groups["body"].Value.TrimEnd();
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }
}
