using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SquadDash;

/// <summary>
/// Fields the AI sends when emitting an INBOX_MESSAGE_JSON block.
/// Timestamp, Id, and Read are generated by the host, not the AI.
/// </summary>
internal sealed class InboxMessageDto
{
    [JsonPropertyName("subject")]
    public string Subject { get; init; } = string.Empty;

    [JsonPropertyName("from")]
    public string From { get; init; } = string.Empty;

    [JsonPropertyName("body")]
    public string Body { get; init; } = string.Empty;

    [JsonPropertyName("attachments")]
    public IReadOnlyList<InboxAttachment> Attachments { get; init; } = [];

    [JsonPropertyName("actions")]
    public IReadOnlyList<InboxAction> Actions { get; init; } = [];
}

/// <summary>
/// Detects and extracts <c>INBOX_MESSAGE_JSON:</c> sentinel blocks from AI responses.
/// Uses the same structural pattern as <see cref="HostCommandParser"/>.
/// </summary>
internal static class InboxMessageParser
{
    private const string Marker = "INBOX_MESSAGE_JSON:";

    private static readonly JsonSerializerOptions ParseOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Attempts to extract an INBOX_MESSAGE_JSON block from <paramref name="text"/>.
    /// Returns true when the sentinel is found and the JSON is valid.
    /// <paramref name="body"/> receives the text before the block (trimmed);
    /// <paramref name="dto"/> receives the parsed payload.
    /// Tolerates arbitrary prose appearing after the closing brace.
    /// When multiple markers are present the last one is used.
    /// </summary>
    internal static bool TryExtract(string text, out string body, out InboxMessageDto? dto)
    {
        body = text;
        dto  = null;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        var normalized = text.Replace("\r\n", "\n").Replace('\r', '\n');

        // Use the last occurrence so that multiple blocks resolve to the final one.
        int markerIdx = normalized.LastIndexOf(Marker, StringComparison.Ordinal);
        if (markerIdx < 0)
            return false;

        int braceStart = normalized.IndexOf('{', markerIdx + Marker.Length);
        if (braceStart < 0)
            return false;

        // Walk the JSON using brace depth so we stop at the true closing brace,
        // regardless of whatever prose or markdown follows it. The model
        // sometimes leaves prose quotes unescaped inside string values; treat
        // those as content rather than letting them corrupt string state.
        int depth    = 0;
        int braceEnd = -1;
        bool inString = false;
        bool escaped  = false;
        for (int i = braceStart; i < normalized.Length; i++)
        {
            char c = normalized[i];
            if (escaped)
            {
                escaped = false;
                continue;
            }
            if (c == '\\' && inString) { escaped = true; continue; }
            if (c == '"')
            {
                if (!inString || IsLikelyJsonStringTerminator(normalized, i))
                    inString = !inString;
                continue;
            }
            if (inString) continue;

            if      (c == '{') depth++;
            else if (c == '}')
            {
                depth--;
                if (depth == 0) { braceEnd = i; break; }
            }
        }

        if (braceEnd < 0)
            return false;

        var jsonText = normalized[braceStart..(braceEnd + 1)];

        try
        {
            var sanitized = SanitizeMalformedStringContent(jsonText);
            dto = JsonSerializer.Deserialize<InboxMessageDto>(sanitized, ParseOptions);
            if (dto is null)
                return false;

            dto = StripNoOpDoneActions(dto);
            body = StripTrailingCodeFence(normalized[..markerIdx].TrimEnd());
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    /// <summary>
    /// Replaces common malformed content inside JSON string values with valid escape
    /// sequences. The AI sometimes emits multi-line prompt text with real newlines
    /// rather than \n, or prose quotes rather than \", which makes the JSON invalid.
    /// </summary>
    private static string SanitizeMalformedStringContent(string json)
    {
        var sb = new System.Text.StringBuilder(json.Length + 64);
        bool inString = false;
        bool escaped  = false;
        for (int i = 0; i < json.Length; i++)
        {
            char c = json[i];
            if (escaped)
            {
                sb.Append(c);
                escaped = false;
                continue;
            }
            if (c == '\\' && inString) { sb.Append(c); escaped = true; continue; }
            if (c == '"')
            {
                if (!inString || IsLikelyJsonStringTerminator(json, i))
                {
                    inString = !inString;
                    sb.Append(c);
                }
                else
                {
                    sb.Append("\\\"");
                }
                continue;
            }
            if (inString)
            {
                if (c == '\r')
                {
                    // Collapse \r\n → \\n, bare \r → \\n
                    if (i + 1 < json.Length && json[i + 1] == '\n') i++;
                    sb.Append("\\n");
                    continue;
                }
                if (c == '\n') { sb.Append("\\n"); continue; }
                if (c == '\t') { sb.Append("\\t"); continue; }
            }
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static bool IsLikelyJsonStringTerminator(string json, int quoteIndex)
    {
        for (int i = quoteIndex + 1; i < json.Length; i++)
        {
            var c = json[i];
            if (char.IsWhiteSpace(c))
                continue;

            return c is ':' or ',' or '}' or ']';
        }

        return true;
    }

    /// <summary>
    /// Strips 'done' actions whose labels are purely acknowledgement-only (e.g. Dismiss, OK, Close).
    /// These add no value — clicking them records nothing and can't launch any agent.
    /// </summary>
    private static readonly System.Collections.Generic.HashSet<string> NoOpDoneLabels =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            "dismiss", "ok", "okay", "close", "cancel", "got it", "done",
            "acknowledge", "acknowledged", "clear", "ignore", "never mind",
            "no thanks", "not now", "skip"
        };

    private static InboxMessageDto StripNoOpDoneActions(InboxMessageDto dto)
    {
        if (dto.Actions.Count == 0)
            return dto;

        var filtered = new System.Collections.Generic.List<InboxAction>(dto.Actions.Count);
        foreach (var action in dto.Actions)
        {
            bool isNoOp = string.Equals(action.RouteMode, "done", System.StringComparison.OrdinalIgnoreCase)
                       && NoOpDoneLabels.Contains(action.Label.Trim());
            if (!isNoOp)
                filtered.Add(action);
        }

        if (filtered.Count == dto.Actions.Count)
            return dto;

        return new InboxMessageDto
        {
            Subject     = dto.Subject,
            From        = dto.From,
            Body        = dto.Body,
            Attachments = dto.Attachments,
            Actions     = filtered,
        };
    }

    /// <summary>
    /// Strips a trailing code-fence opening line (``` or ```lang) if present,
    /// so that <c>body</c> does not contain the fence that wraps the INBOX block.
    /// </summary>
    private static string StripTrailingCodeFence(string text)
    {
        if (text.Length == 0)
            return text;

        int lastNewline = text.LastIndexOf('\n');
        var lastLine    = lastNewline < 0 ? text : text[(lastNewline + 1)..];
        var trimmed     = lastLine.TrimStart();
        if (trimmed.StartsWith("```", StringComparison.Ordinal))
        {
            var before = lastNewline < 0 ? string.Empty : text[..lastNewline];
            return before.TrimEnd();
        }
        return text;
    }
}
